# Generated by Django 6.0 on 2025-12-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_material', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_mao_de_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imposto_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preco_venda_sugerido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margem_real_atigida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
