# Generated by Django 6.0 on 2025-12-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MargemPredict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulaçãoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imposto_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_imposto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_simulacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PrevisaoServico',
        ),
    ]
